#!/bin/bash

export DE=openbox

# Display Fix for Big TV and little monitor on the left of it
#/bin/display-settings.sh


# Dbus fix
if [ -z "$DBUS_SESSION_BUS_ADDRESS" ]; then
    eval "$(dbus-launch --sh-syntax --exit-with-session)"
fi

/usr/bin/xdg-user-dirs-update

# configure obmenu user
#sed -i 's/live/'$(whoami)'/' ~/.config/obmenu-generator/schema.pl \
			     ~/.config/obmenu-generator/config.pl  
# start openbox
/usr/bin/openbox-session > ~/.openbox_startup.log 2>&1

# enable swap
#swapon /dev/sda3
